### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by maximpetrov** [tyushin/TrainTimetable#1]
1. Сеттер для имени станции - лишний.
1. Вообще не стоит делать сеттеры всем полям "на всякий случай". Уберите лишние сеттеры из `Trains`.
1. Если Вы принимаете в методе изменяемый объект, особенно коллекции как `ArrayList`, и хотите сохранить его в поле класса, нужно сделать его копию. Тоже самое относится и к возвращению полей-коллекций из методов.
1. `realTime` не использует поля класса, его можно сделать статическим. Кстати, что Вам помешало завести отдельный класс для представления времени? Для станции, являющейся всего лишь строкой, Вы класс завели.
1. В методе `findTrain` лучше использовать циклы `for` в варианте `for-each`.
1. Достаточно одной переменной для хранения ближайшего времени, если хранить модуль разности между заданным временем и временем отправления поезда (и сравнивать тоже с модулем разности).
1. Лучше сначала определить, ближайший ли это поезд на текущий момент, а уже потом начинать перебирать его станции.
1. Проверку наличия станции в маршруте поезда стоит перенести в `Trains`.
1. Нет тестов.

**Comment by tyushin** [comment]
1.  Убрал сеттер для имени станции.
2.  Убрал лишние сеттеры.
3. Сделал копии.
4. Добавил класс время.
5. Использовал for-each.
6-8. Cначала, я отсортировал список по времени, поэтому когда он идёт по порядку,он сразу находит ближайший поезд.
(9.) Добавил тесты.

**Comment by tyushin** [comment]
Сделал 2-ое задание (Tail 9 вариант)

2017-05-23 16:52 GMT+03:00 Maxim Petrov <notifications@github.com>:

**Comment by tyushin** [comment]
Исправил замечания во 2-ом задании.

2017-06-11 22:45 GMT+03:00 Артём Тюшин <artart998@gmail.com>:
